###
POST http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
    "username": 1,
    "password": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
POST http://localhost:8080/auth/refresh-token HTTP/1.1


GET http://localhost:8080/test-error HTTP/1.1
