apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-deployment
  labels:
    app: sso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth:0.1 # docker image name
          ports:
            - containerPort: 8080
